[package]
name = "reverse"
version = "0.1.0"
authors = ["kfly8 <kfly@cpan.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
